
const mockData = [
{ 
  id: 1,
  productName: 'White Bad Bats Tee 1',
  productPrice: '$30.00 USD',
  productImage: '/elpiloto-badbrain-tee.png',
  productStock: 40,
  productType: 'Tee',
  productStockS: 10,
  productStockM: 10,
  productStockL: 10,
  productStockXL: 10,
},
{ 
  id: 2,
  productName: 'Black Bad Bats Tee 2',
  productPrice: '$30.00 USD',
  productImage: '/elpiloto-badbrain-tee-black.jpeg',
  productStock: 40,
  productType: 'Tee',
  productStockS: 10,
  productStockM: 10,
  productStockL: 10,
  productStockXL: 10,
},
{ 
  id: 3,
  productName: 'White Bad Bats Tee 3',
  productPrice: '$30.00 USD',
  productImage: '/elpiloto-badbrain-tee.png',
  productStock: 40,
  productType: 'Tee',
  productStockS: 10,
  productStockM: 10,
  productStockL: 10,
  productStockXL: 10,
},
{ 
  id: 4,
  productName: 'Black Bad Bats Tee 4',
  productPrice: '$30.00 USD',
  productImage: '/elpiloto-badbrain-tee-black.jpeg',
  productStock: 40,
  productType: 'Tee',
  productStockS: 10,
  productStockM: 10,
  productStockL: 10,
  productStockXL: 10,
},
{ 
  id: 5,
  productName: 'White Bad Bats Tee 5',
  productPrice: '$30.00 USD',
  productImage: '/elpiloto-badbrain-tee.png',
  productStock: 40,
  productType: 'Tee',
  productStockS: 10,
  productStockM: 10,
  productStockL: 10,
  productStockXL: 10,
},
{ 
  id: 6,
  productName: 'Black Bad Bats Tee 6',
  productPrice: '$30.00 USD',
  productImage: '/elpiloto-badbrain-tee-black.jpeg',
  productStock: 40,
  productType: 'Tee',
  productStockS: 10,
  productStockM: 10,
  productStockL: 10,
  productStockXL: 10,
},
{ 
  id: 7,
  productName: 'White Bad Bats Tee 7',
  productPrice: '$30.00 USD',
  productImage: '/elpiloto-badbrain-tee.png',
  productStock: 40,
  productType: 'Tee',
  productStockS: 10,
  productStockM: 10,
  productStockL: 10,
  productStockXL: 10,
},
{ 
  id: 8,
  productName: 'Black Bad Bats Tee 8',
  productPrice: '$30.00 USD',
  productImage: '/elpiloto-badbrain-tee-black.jpeg',
  productStock: 40,
  productType: 'Tee',
  productStockS: 10,
  productStockM: 10,
  productStockL: 10,
  productStockXL: 10,
},
]

export default mockData